__Day 3 Assignment - Solution__

# Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.


In [1]:
import numpy as np
arr = np.arange(2, 50, 3)

print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


___________

# Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.


In [2]:
import numpy as np

# creating a 2 empty list:
lst_1 = []
lst_2 = []

# getting values for lst_1 from user:
for i in range(5):
    x=int(input("\nEnter the value for lst_1 : "))
    lst_1.append(x)

# getting values for lst_2 from user:
for i in range(5):
    x=int(input("\nEnter the value for lst_2 : "))
    lst_2.append(x)

# converting list into array:
arr_1 = np.array(lst_1)
arr_2 = np.array(lst_2)

# concatenating 2 array:
arr = np.concatenate((arr_1, arr_2))
print("\nArray value for concatenated arr :",arr)

# sorting up concatenated array
sortArr = np.sort(arr)
print("\nSorted Array for concatenated arr :",sortArr)



Enter the value for lst_1 : 47

Enter the value for lst_1 : 32

Enter the value for lst_1 : 67

Enter the value for lst_1 : 58

Enter the value for lst_1 : 69

Enter the value for lst_2 : 88

Enter the value for lst_2 : 44

Enter the value for lst_2 : 09

Enter the value for lst_2 : 20

Enter the value for lst_2 : 46

Array value for concatenated arr : [47 32 67 58 69 88 44  9 20 46]

Sorted Array for concatenated arr : [ 9 20 32 44 46 47 58 67 69 88]



___________

# Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.


In [3]:
import numpy as np

# creating a 2d array
arr = np.array([[1,2,3],[1,3,5]])

# Printing array dimensions (axes)
print("\nDimensions in array : ", arr.ndim)
 
# Printing size of array
print("\nSize of array : ", arr.size)


Dimensions in array :  2

Size of array :  6


____________

# Questions 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [4]:
arr = np.array([ [1,2,3,4,5,6,7,8,9] ])

print(arr,arr.shape) 

print()

arr = arr.reshape(3,3) 

print(arr,arr.shape)

[[1 2 3 4 5 6 7 8 9]] (1, 9)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


_____________

# Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()


In [5]:

arr1 = np.array([ [1,1,1] , [2,2,2] , [3,3,3] ])
arr2 = np.array([ [4,4,4] , [5,5,5] , [6,6,6] ])
print(np.vstack((arr1,arr2))) # Stack the arrays in a row-wise sequence
print() 
print(np.hstack((arr1,arr2))) # Stack the arrays in a column-wise sequence

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]
 [6 6 6]]

[[1 1 1 4 4 4]
 [2 2 2 5 5 5]
 [3 3 3 6 6 6]]


________________

# Questions 6:
How to get unique items and counts of unique items?

In [6]:
arr = np.array([ [1,2,2] , [1,2,2] , [5,6,6] ])

print(np.unique(arr,return_counts=True))

(array([1, 2, 5, 6]), array([2, 4, 1, 2], dtype=int64))


________________